package top.dongzeviva.zaofans.model;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.util.Date;

public class UcUser extends Entity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_openid
     *
     * @mbggenerated
     */
    private String wechatOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_union_id
     *
     * @mbggenerated
     */
    private String wechatUnionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_nickname
     *
     * @mbggenerated
     */
    private String wechatNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_portrait
     *
     * @mbggenerated
     */
    private String wechatPortrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_sex
     *
     * @mbggenerated
     */
    private Integer wechatSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_subscribe
     *
     * @mbggenerated
     */
    private Integer wechatSubscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_language
     *
     * @mbggenerated
     */
    private String wechatLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_city
     *
     * @mbggenerated
     */
    private String wechatCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_country
     *
     * @mbggenerated
     */
    private String wechatCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_province
     *
     * @mbggenerated
     */
    private String wechatProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_subscribe_time
     *
     * @mbggenerated
     */
    private Date wechatSubscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_remark
     *
     * @mbggenerated
     */
    private String wechatRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.wechat_groupid
     *
     * @mbggenerated
     */
    private Integer wechatGroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_sex
     *
     * @mbggenerated
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_birthday
     *
     * @mbggenerated
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_mobile
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_balance
     *
     * @mbggenerated
     */
    private BigDecimal userBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_vip_level
     *
     * @mbggenerated
     */
    private Integer userVipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_portrait
     *
     * @mbggenerated
     */
    private String userPortrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_city
     *
     * @mbggenerated
     */
    private String userCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.user_card_no
     *
     * @mbggenerated
     */
    private String userCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.id
     *
     * @return the value of uc_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.id
     *
     * @param id the value for uc_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_openid
     *
     * @return the value of uc_user.wechat_openid
     *
     * @mbggenerated
     */
    public String getWechatOpenid() {
        return wechatOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_openid
     *
     * @param wechatOpenid the value for uc_user.wechat_openid
     *
     * @mbggenerated
     */
    public void setWechatOpenid(String wechatOpenid) {
        this.wechatOpenid = wechatOpenid == null ? null : wechatOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_union_id
     *
     * @return the value of uc_user.wechat_union_id
     *
     * @mbggenerated
     */
    public String getWechatUnionId() {
        return wechatUnionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_union_id
     *
     * @param wechatUnionId the value for uc_user.wechat_union_id
     *
     * @mbggenerated
     */
    public void setWechatUnionId(String wechatUnionId) {
        this.wechatUnionId = wechatUnionId == null ? null : wechatUnionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_nickname
     *
     * @return the value of uc_user.wechat_nickname
     *
     * @mbggenerated
     */
    public String getWechatNickname() {
        return wechatNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_nickname
     *
     * @param wechatNickname the value for uc_user.wechat_nickname
     *
     * @mbggenerated
     */
    public void setWechatNickname(String wechatNickname) {
        this.wechatNickname = wechatNickname == null ? null : wechatNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_portrait
     *
     * @return the value of uc_user.wechat_portrait
     *
     * @mbggenerated
     */
    public String getWechatPortrait() {
        return wechatPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_portrait
     *
     * @param wechatPortrait the value for uc_user.wechat_portrait
     *
     * @mbggenerated
     */
    public void setWechatPortrait(String wechatPortrait) {
        this.wechatPortrait = wechatPortrait == null ? null : wechatPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_sex
     *
     * @return the value of uc_user.wechat_sex
     *
     * @mbggenerated
     */
    public Integer getWechatSex() {
        return wechatSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_sex
     *
     * @param wechatSex the value for uc_user.wechat_sex
     *
     * @mbggenerated
     */
    public void setWechatSex(Integer wechatSex) {
        this.wechatSex = wechatSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_subscribe
     *
     * @return the value of uc_user.wechat_subscribe
     *
     * @mbggenerated
     */
    public Integer getWechatSubscribe() {
        return wechatSubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_subscribe
     *
     * @param wechatSubscribe the value for uc_user.wechat_subscribe
     *
     * @mbggenerated
     */
    public void setWechatSubscribe(Integer wechatSubscribe) {
        this.wechatSubscribe = wechatSubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_language
     *
     * @return the value of uc_user.wechat_language
     *
     * @mbggenerated
     */
    public String getWechatLanguage() {
        return wechatLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_language
     *
     * @param wechatLanguage the value for uc_user.wechat_language
     *
     * @mbggenerated
     */
    public void setWechatLanguage(String wechatLanguage) {
        this.wechatLanguage = wechatLanguage == null ? null : wechatLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_city
     *
     * @return the value of uc_user.wechat_city
     *
     * @mbggenerated
     */
    public String getWechatCity() {
        return wechatCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_city
     *
     * @param wechatCity the value for uc_user.wechat_city
     *
     * @mbggenerated
     */
    public void setWechatCity(String wechatCity) {
        this.wechatCity = wechatCity == null ? null : wechatCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_country
     *
     * @return the value of uc_user.wechat_country
     *
     * @mbggenerated
     */
    public String getWechatCountry() {
        return wechatCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_country
     *
     * @param wechatCountry the value for uc_user.wechat_country
     *
     * @mbggenerated
     */
    public void setWechatCountry(String wechatCountry) {
        this.wechatCountry = wechatCountry == null ? null : wechatCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_province
     *
     * @return the value of uc_user.wechat_province
     *
     * @mbggenerated
     */
    public String getWechatProvince() {
        return wechatProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_province
     *
     * @param wechatProvince the value for uc_user.wechat_province
     *
     * @mbggenerated
     */
    public void setWechatProvince(String wechatProvince) {
        this.wechatProvince = wechatProvince == null ? null : wechatProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_subscribe_time
     *
     * @return the value of uc_user.wechat_subscribe_time
     *
     * @mbggenerated
     */
    public Date getWechatSubscribeTime() {
        return wechatSubscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_subscribe_time
     *
     * @param wechatSubscribeTime the value for uc_user.wechat_subscribe_time
     *
     * @mbggenerated
     */
    public void setWechatSubscribeTime(Date wechatSubscribeTime) {
        this.wechatSubscribeTime = wechatSubscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_remark
     *
     * @return the value of uc_user.wechat_remark
     *
     * @mbggenerated
     */
    public String getWechatRemark() {
        return wechatRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_remark
     *
     * @param wechatRemark the value for uc_user.wechat_remark
     *
     * @mbggenerated
     */
    public void setWechatRemark(String wechatRemark) {
        this.wechatRemark = wechatRemark == null ? null : wechatRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.wechat_groupid
     *
     * @return the value of uc_user.wechat_groupid
     *
     * @mbggenerated
     */
    public Integer getWechatGroupid() {
        return wechatGroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.wechat_groupid
     *
     * @param wechatGroupid the value for uc_user.wechat_groupid
     *
     * @mbggenerated
     */
    public void setWechatGroupid(Integer wechatGroupid) {
        this.wechatGroupid = wechatGroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_name
     *
     * @return the value of uc_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_name
     *
     * @param userName the value for uc_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_sex
     *
     * @return the value of uc_user.user_sex
     *
     * @mbggenerated
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_sex
     *
     * @param userSex the value for uc_user.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_birthday
     *
     * @return the value of uc_user.user_birthday
     *
     * @mbggenerated
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_birthday
     *
     * @param userBirthday the value for uc_user.user_birthday
     *
     * @mbggenerated
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_mobile
     *
     * @return the value of uc_user.user_mobile
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_mobile
     *
     * @param userMobile the value for uc_user.user_mobile
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_balance
     *
     * @return the value of uc_user.user_balance
     *
     * @mbggenerated
     */
    public BigDecimal getUserBalance() {
        return userBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_balance
     *
     * @param userBalance the value for uc_user.user_balance
     *
     * @mbggenerated
     */
    public void setUserBalance(BigDecimal userBalance) {
        this.userBalance = userBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_vip_level
     *
     * @return the value of uc_user.user_vip_level
     *
     * @mbggenerated
     */
    public Integer getUserVipLevel() {
        return userVipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_vip_level
     *
     * @param userVipLevel the value for uc_user.user_vip_level
     *
     * @mbggenerated
     */
    public void setUserVipLevel(Integer userVipLevel) {
        this.userVipLevel = userVipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_portrait
     *
     * @return the value of uc_user.user_portrait
     *
     * @mbggenerated
     */
    public String getUserPortrait() {
        return userPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_portrait
     *
     * @param userPortrait the value for uc_user.user_portrait
     *
     * @mbggenerated
     */
    public void setUserPortrait(String userPortrait) {
        this.userPortrait = userPortrait == null ? null : userPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_password
     *
     * @return the value of uc_user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_password
     *
     * @param userPassword the value for uc_user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_city
     *
     * @return the value of uc_user.user_city
     *
     * @mbggenerated
     */
    public String getUserCity() {
        return userCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_city
     *
     * @param userCity the value for uc_user.user_city
     *
     * @mbggenerated
     */
    public void setUserCity(String userCity) {
        this.userCity = userCity == null ? null : userCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.user_card_no
     *
     * @return the value of uc_user.user_card_no
     *
     * @mbggenerated
     */
    public String getUserCardNo() {
        return userCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.user_card_no
     *
     * @param userCardNo the value for uc_user.user_card_no
     *
     * @mbggenerated
     */
    public void setUserCardNo(String userCardNo) {
        this.userCardNo = userCardNo == null ? null : userCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.create_time
     *
     * @return the value of uc_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.create_time
     *
     * @param createTime the value for uc_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.update_time
     *
     * @return the value of uc_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.update_time
     *
     * @param updateTime the value for uc_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}